### ISSUE TITLE
Manual Approval Title Update failure

### ISSUE THREAD

**Issue by BenjaminRuby** [boomerang-io/roadmap#219] opened 2021-08-31 16:24 UTC
**Describe the bug**
Currently unable to change the title for a manual approval task

**To Reproduce**
Drag and drop a manual approval task onto a flow. Change the title and then save the workflow, creating a new revision. Then go back and try to change the title again and save the form. You should get a daks error there

**Expected behavior**
As for the other tasks, a user should be able to give a custom name to a task.

**Screenshots**
![image (24).png](https://images.zenhubusercontent.com/5f997c3d144cc0adc7d23276/fed4062e-21e4-4167-891a-a498ec67a6d0)

**Comment by Okisa** [comment] 2021-09-01 14:54
Hi @BenjaminRuby 
I'm not able to reproduce in dev, can you share which workflow you received this error?
![manual-task.gif](https://images.zenhubusercontent.com/5fdb5cec3fe13a19b650e279/b2e67da1-7dc9-4593-a10b-f30221257cf8)

**Comment by tlawrie** [comment] 2021-09-17 04:39
Hey @Okisa is this making it into 3.4 or 3.4.1 as a bug fix?

**Comment by Okisa** [comment] 2021-09-20 12:38
Still not able to reproduce locally or in dev.

**Comment by tlawrie** [comment] 2021-09-28 02:31
Hi @BenjaminRuby is this still a concern?

**Comment by marcusdroy** [comment] 2021-09-30 21:24
@Okisa @BenjaminRuby I believe this is still an issue in live for a certain workflow

**Comment by amhudson** [comment] 2021-10-14 18:28
fixed with 3.1.67

**Comment by dlsyliu** [comment] 2021-10-15 01:10
Thank you guys working on it, let me inform the user that status.

**Comment by tlawrie** [comment] 2021-11-18 03:30
Resolved and verified. Part of Release 3.4.1

**Closed by tlawrie** 2021-11-18 03:30 UTC
Labels: bug, project: flow
